spring.main.banner-mode: off

server:
  port: 7003

logging:
   level:
     root: INFO
     com.github.kerner1000: DEBUG

app:
  taxonomy-provider:
    host: localhost
    port: 7005

spring.jpa.hibernate.ddl-auto: update

spring.datasource:
  url: jdbc:mysql://localhost:3307/etoro-stats
  username: etoro-stats
  password: etoro

spring.datasource.hikari.initializationFailTimeout: 60000
spring.jpa.database: mysql
---
spring:
  config:
    activate:
      on-profile: docker
  datasource:
    url: jdbc:mysql://mysql:3307/etoro-stats
    username: etoro-stats
    password: etoro

server.port: 8080

app:
  taxonomy-provider:
    host: yahoo-taxonomy
    port: 8080
