spring.main.banner-mode: off

logging:
   level:
     root: INFO
     com.github.kerner1000: DEBUG

server.port: 8080

app:
  composite-service:
    host: localhost
    port: 7070

---
spring.profiles: docker

app:
  composite-service:
    host: composite