spring.main.banner-mode: off

server:
  port: 7004

logging:
  level:
    root: INFO
    com.github.kerner1000: DEBUG

# Strongly recommend to set this property to "none" in a production environment!
spring.jpa.hibernate.ddl-auto: update
spring.jpa.database: mysql

spring.datasource:
  url: jdbc:mysql://localhost:3307/etoro-stats
  username: etoro-stats
  password: etoro

spring.datasource.hikari.initializationFailTimeout: 60000

---
spring.profiles: docker

server.port: 8080

spring.datasource:
  url: jdbc:mysql://mysql:3307/etoro-stats
  username: etoro-stats
  password: etoro
